export type ReadingType = 'paper' | 'blog' | 'video' | 'article' | 'essay' | 'guide'

export type Reading = {
  title: string
  author: string
  year?: number
  url: string
  type: ReadingType
}

export type Week = {
  number: number
  title: string
  label: string
  comingSoon?: boolean
  objectives?: string[]
  core?: Reading[]
  recommended?: Reading[]
  further?: Reading[]
}

export const weeks: Week[] = [
  {
    number: 0,
    title: 'Introduction to Machine Learning',
    label: 'Self-Paced',
    objectives: [
      'Explain how neural networks are trained at a high level',
      'Describe the basic transformer architecture',
    ],
    core: [
      {
        title: 'Neural Networks (Chapters 1-6)',
        author: '3Blue1Brown',
        year: 2024,
        url: 'https://youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'What is Self-Supervised Learning?',
        author: 'CodeBasics',
        year: 2021,
        url: 'https://youtu.be/sJzuNAisXHA',
        type: 'video',
      },
      {
        title: 'Transformers from Scratch',
        author: 'Brandon Rohrer',
        year: 2021,
        url: 'https://e2eml.school/transformers.html',
        type: 'guide',
      },
      {
        title: 'The Spelled-Out Intro to Neural Networks and Backpropagation',
        author: 'Andrej Karpathy',
        year: 2022,
        url: 'https://youtu.be/VMj-3S1tku0',
        type: 'video',
      },
      {
        title: 'Machine Learning for Humans, Part 2.1: Supervised Learning',
        author: 'Maini & Sabri',
        year: 2017,
        url: 'https://medium.com/@v_maini/supervised-learning-740383a2feab',
        type: 'article',
      },
    ],
  },
  {
    number: 1,
    title: 'Transformative AI and Current Trajectory',
    label: 'Week 1',
    objectives: [
      'Describe current AI capability trends and their real-world impacts',
      'Understand arguments for acceleration versus slowdown trajectories',
      'Comprehend scaling drivers: compute, data, algorithmic efficiency, and inference-time scaling',
    ],
    core: [
      {
        title: 'METR Time Horizon',
        author: 'METR',
        year: 2026,
        url: 'https://metr.org/time-horizons/',
        type: 'article',
      },
      {
        title: 'Epoch AI Trends Page',
        author: 'Epoch AI',
        year: 2025,
        url: 'https://epochai.org/trends',
        type: 'article',
      },
      {
        title: 'Can AI Scaling Continue Through 2030?',
        author: 'Epoch AI',
        year: 2024,
        url: 'https://epoch.ai/blog/can-ai-scaling-continue-through-2030',
        type: 'blog',
      },
      {
        title: 'The Power of Intelligence',
        author: 'Eliezer Yudkowsky',
        year: 2007,
        url: 'https://youtu.be/q9Figerh89g?si=9gOTbCyKqrbU6nPp',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'What Will AI Look Like in 2030?',
        author: 'Epoch AI',
        year: 2025,
        url: 'https://epoch.ai/blog/what-will-ai-look-like-in-2030',
        type: 'blog',
      },
      {
        title: 'From AGI to Superintelligence: The Intelligence Explosion',
        author: 'Leopold Aschenbrenner',
        year: 2024,
        url: 'https://situational-awareness.ai/from-agi-to-superintelligence/',
        type: 'essay',
      },
      {
        title: 'Inference Scaling and the Log-x Chart',
        author: 'Toby Ord',
        year: 2025,
        url: 'https://forum.effectivealtruism.org/posts/zNymXezwySidkeRun/inference-scaling-and-the-log-x-chart',
        type: 'essay',
      },
    ],
    further: [
      {
        title: 'Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity',
        author: 'METR',
        year: 2025,
        url: 'https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/',
        type: 'article',
      },
      {
        title: 'Future ML Systems Will Be Qualitatively Different',
        author: 'Jacob Steinhardt',
        year: 2022,
        url: 'https://bounded-regret.ghost.io/future-ml-systems-will-be-qualitatively-different/',
        type: 'blog',
      },
      {
        title: 'Neural Scaling Laws and GPT-3',
        author: 'Kaplan',
        year: 2020,
        url: 'https://www.youtube.com/watch?v=QMqPAM_knrE',
        type: 'video',
      },
      {
        title: 'Training Compute-Optimal Large Language Models',
        author: 'Hoffmann et al. (DeepMind)',
        year: 2022,
        url: 'https://arxiv.org/pdf/2203.15556.pdf',
        type: 'paper',
      },
      {
        title: 'Biological Anchors: A Trick That Might Or Might Not Work',
        author: 'Scott Alexander',
        year: 2022,
        url: 'https://astralcodexten.substack.com/p/biological-anchors-a-trick-that-might',
        type: 'blog',
      },
      {
        title: 'Explaining Neural Scaling Laws',
        author: 'Bahri et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2102.06701',
        type: 'paper',
      },
      {
        title: 'The Hanson-Yudkowsky AI-Foom Debate',
        author: 'Hanson & Yudkowsky',
        year: 2008,
        url: 'https://intelligence.org/files/AIFoomDebate.pdf',
        type: 'essay',
      },
    ],
  },
  {
    number: 2,
    title: 'Outer Alignment',
    label: 'Week 2',
    objectives: [
      'Understand the gap between intended goals and proxy training objectives',
      'Identify major outer alignment failure modes: specification gaming, reward hacking',
      'Evaluate how RLHF and reward modeling advance but don\'t fully resolve alignment',
    ],
    core: [
      {
        title: 'Specification Gaming: The Flip Side of AI Ingenuity',
        author: 'DeepMind',
        year: 2020,
        url: 'https://www.deepmind.com/blog/specification-gaming-the-flip-side-of-ai-ingenuity',
        type: 'blog',
      },
      {
        title: 'Aligning Language Models to Follow Instructions',
        author: 'OpenAI',
        year: 2022,
        url: 'https://openai.com/blog/instruction-following/',
        type: 'blog',
      },
      {
        title: 'Language Models Learn to Mislead Humans via RLHF',
        author: 'Wen et al.',
        year: 2024,
        url: 'https://arxiv.org/pdf/2409.12822',
        type: 'paper',
      },
      {
        title: 'Large Language Models Can Strategically Deceive Their Users When Put Under Pressure',
        author: 'Apollo Research',
        year: 2023,
        url: 'https://arxiv.org/pdf/2311.07590',
        type: 'paper',
      },
    ],
    recommended: [
      {
        title: 'Deep RL From Human Preferences',
        author: 'Christiano et al.',
        year: 2017,
        url: 'https://openai.com/blog/deep-reinforcement-learning-from-human-preferences/',
        type: 'blog',
      },
      {
        title: 'Playing the Training Game',
        author: 'Kelsey Piper',
        year: 2023,
        url: 'https://www.planned-obsolescence.org/the-training-game/',
        type: 'essay',
      },
      {
        title: 'Natural Emergent Misalignment From Reward Hacking in Production RL',
        author: 'Anthropic & Redwood Research',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.18397',
        type: 'paper',
      },
      {
        title: 'Constitutional AI: Harmlessness From AI Feedback',
        author: 'Anthropic',
        year: 2022,
        url: 'https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback',
        type: 'paper',
      },
      {
        title: 'Open Problems and Fundamental Limitations of RLHF',
        author: 'Casper et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2307.15217',
        type: 'paper',
      },
    ],
    further: [
      {
        title: 'Sycophancy to Subterfuge: Investigating Reward Tampering in Language Models',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/reward-tampering',
        type: 'paper',
      },
      {
        title: 'Scaling Laws for Reward Model Overoptimization',
        author: 'OpenAI',
        year: 2022,
        url: 'https://arxiv.org/abs/2210.10760',
        type: 'paper',
      },
      {
        title: 'Concrete Problems in AI Safety',
        author: 'Amodei et al.',
        year: 2016,
        url: 'https://arxiv.org/abs/1606.06565',
        type: 'paper',
      },
      {
        title: 'Scalable Agent Alignment via Reward Modeling',
        author: 'DeepMind',
        year: 2018,
        url: 'https://arxiv.org/abs/1811.07871',
        type: 'paper',
      },
    ],
  },
  {
    number: 3,
    title: 'Inner Alignment',
    label: 'Week 3',
    objectives: [
      'Describe key failure modes: mesa-optimization, goal misgeneralization, deceptive alignment',
      'Evaluate empirical evidence that models fake alignment and persist deceptively through safety training',
      'Assess why standard safety training may be insufficient against deceptively misaligned behavior',
    ],
    core: [
      {
        title: 'The OTHER AI Alignment Problem: Mesa-Optimizers and Inner Alignment',
        author: 'Robert Miles',
        year: 2021,
        url: 'https://www.youtube.com/watch?v=bJLcIBixGj8',
        type: 'video',
      },
      {
        title: 'Alignment Faking in Large Language Models',
        author: 'Anthropic & Redwood Research',
        year: 2024,
        url: 'https://arxiv.org/abs/2412.14093',
        type: 'paper',
      },
      {
        title: 'Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training',
        author: 'Anthropic',
        year: 2024,
        url: 'https://arxiv.org/abs/2401.05566',
        type: 'paper',
      },
      {
        title: 'From Shortcuts to Sabotage: Natural Emergent Misalignment From Reward Hacking',
        author: 'Anthropic',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.18397',
        type: 'paper',
      },
    ],
    recommended: [
      {
        title: 'ML Systems Will Have Weird Failure Modes',
        author: 'Jacob Steinhardt',
        year: 2022,
        url: 'https://bounded-regret.ghost.io/ml-systems-will-have-weird-failure-modes-2/',
        type: 'blog',
      },
      {
        title: 'Sycophancy to Subterfuge: Investigating Reward Tampering in Language Models',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/reward-tampering',
        type: 'paper',
      },
      {
        title: 'Emergent Misalignment: Narrow Finetuning Can Produce Broadly Misaligned LLMs',
        author: 'Betley et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2502.07209',
        type: 'paper',
      },
      {
        title: 'Frontier Models are Capable of In-Context Scheming',
        author: 'Apollo Research',
        year: 2024,
        url: 'https://www.apolloresearch.ai/research/frontier-models-are-capable-of-in-context-scheming/',
        type: 'article',
      },
      {
        title: 'Distillation of "How Likely is Deceptive Alignment?"',
        author: 'Evan Hubinger',
        year: 2022,
        url: 'https://www.lesswrong.com/posts/XKraEJrQRfzbCtzKN/distillation-of-how-likely-is-deceptive-alignment',
        type: 'essay',
      },
    ],
    further: [
      {
        title: 'Why Alignment Could Be Hard With Modern Deep Learning',
        author: 'Ajeya Cotra',
        year: 2021,
        url: 'https://www.alignmentforum.org/posts/CoZhXrhpQxpy88Sq8/why-alignment-could-be-hard-with-modern-deep-learning',
        type: 'essay',
      },
      {
        title: 'Goal Misgeneralization: Why Correct Specifications Aren\'t Enough for Correct Goals',
        author: 'Shah et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2210.01790',
        type: 'paper',
      },
      {
        title: 'The Alignment Problem From a Deep Learning Perspective',
        author: 'Ngo et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2209.00626',
        type: 'paper',
      },
      {
        title: 'Goal Misgeneralization in Deep Reinforcement Learning',
        author: 'Langosco et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2105.14111',
        type: 'paper',
      },
      {
        title: 'Optimal Policies Tend to Seek Power',
        author: 'Turner et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/1906.01820',
        type: 'paper',
      },
      {
        title: 'Language Models as Agent Models',
        author: 'Andreas',
        year: 2022,
        url: 'https://arxiv.org/abs/2212.01681',
        type: 'paper',
      },
    ],
  },
  {
    number: 4,
    title: 'Threat Models',
    label: 'Week 4',
    objectives: [
      'Articulate the orthogonality thesis and instrumental convergence and their centrality to advanced AI risk',
      'Connect technical alignment failures to real-world harm scenarios at scale',
    ],
    core: [
      {
        title: 'What is the Orthogonality Thesis?',
        author: 'AISafety.info',
        url: 'https://aisafety.info/questions/6568/What-is-the-orthogonality-thesis',
        type: 'article',
      },
      {
        title: 'Why Would AI Want to do Bad Things? Instrumental Convergence',
        author: 'Robert Miles',
        year: 2018,
        url: 'https://www.youtube.com/watch?v=ZeecOKBus3Q',
        type: 'video',
      },
      {
        title: 'Statement on AI Risk',
        author: 'Center for AI Safety',
        year: 2023,
        url: 'https://safe.ai/work/statement-on-ai-risk',
        type: 'article',
      },
      {
        title: 'An Overview of Catastrophic AI Risks',
        author: 'Center for AI Safety',
        year: 2023,
        url: 'https://arxiv.org/abs/2306.12001',
        type: 'paper',
      },
      {
        title: 'We\'re Not Ready for Superintelligence',
        author: 'AI in Context',
        year: 2025,
        url: 'https://www.youtube.com/watch?v=5KVDDfAkRgc',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'AI 2027',
        author: 'AI Futures Project',
        year: 2025,
        url: 'https://ai-2027.com/',
        type: 'article',
      },
      {
        title: 'The Problem',
        author: 'MIRI',
        year: 2025,
        url: 'https://intelligence.org/the-problem/',
        type: 'article',
      },
      {
        title: 'Intelligence and Stupidity: The Orthogonality Thesis',
        author: 'Robert Miles',
        year: 2018,
        url: 'https://www.youtube.com/watch?v=hEUO6pjwFOo',
        type: 'video',
      },
      {
        title: 'The Basic AI Drives',
        author: 'Steve Omohundro',
        year: 2008,
        url: 'https://selfawaresystems.com/wp-content/uploads/2008/01/ai_drives_final.pdf',
        type: 'paper',
      },
      {
        title: 'Gradual Disempowerment',
        author: 'Kulveit et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2501.16946',
        type: 'paper',
      },
      {
        title: 'The Superintelligent Will: Motivation and Instrumental Rationality in Advanced Artificial Agents',
        author: 'Nick Bostrom',
        year: 2012,
        url: 'https://nickbostrom.com/superintelligentwill.pdf',
        type: 'paper',
      },
      {
        title: 'Existential Risk from Power-Seeking AI',
        author: 'Joe Carlsmith',
        year: 2022,
        url: 'https://arxiv.org/abs/2206.13353',
        type: 'paper',
      },
    ],
    further: [
      {
        title: 'Instrumental Convergence',
        author: 'Eliezer Yudkowsky',
        year: 2025,
        url: 'https://arbital.com/p/instrumental_convergence/',
        type: 'article',
      },
      {
        title: 'Why Would AI "Aim" To Defeat Humanity?',
        author: 'Cold Takes',
        year: 2022,
        url: 'https://www.cold-takes.com/why-would-ai-aim-to-defeat-humanity/',
        type: 'blog',
      },
      {
        title: 'AI Could Defeat All Of Us Combined',
        author: 'Cold Takes',
        year: 2022,
        url: 'https://www.cold-takes.com/ai-could-defeat-all-of-us-combined/',
        type: 'blog',
      },
      {
        title: 'Two Types of AI Existential Risk: Decisive and Accumulative',
        author: 'Atoosa Kasirzadeh',
        year: 2025,
        url: 'https://arxiv.org/abs/2401.07836',
        type: 'paper',
      },
      {
        title: 'International AI Safety Report 2026',
        author: 'International AI Safety Report',
        year: 2026,
        url: 'https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026',
        type: 'article',
      },
      {
        title: 'The Vulnerable World Hypothesis',
        author: 'Nick Bostrom',
        year: 2019,
        url: 'https://nickbostrom.com/papers/vulnerable.pdf',
        type: 'paper',
      },
      {
        title: 'AI-Enabled Coups: How a Small Group Could Use AI to Seize Power',
        author: 'Forethought',
        year: 2025,
        url: 'https://www.forethought.org/research/ai-enabled-coups-how-a-small-group-could-use-ai-to-seize-power',
        type: 'article',
      },
      {
        title: 'Impact of AI on Cyber Threat From Now to 2027',
        author: 'NCSC',
        year: 2025,
        url: 'https://www.ncsc.gov.uk/report/impact-ai-cyber-threat-now-2027',
        type: 'article',
      },
      {
        title: 'How AI Threatens Democracy',
        author: 'Kreps & Kriner',
        year: 2023,
        url: 'https://www.journalofdemocracy.org/articles/how-ai-threatens-democracy/',
        type: 'article',
      },
      {
        title: 'Can Democracy Survive the Disruptive Power of AI?',
        author: 'Carnegie Endowment',
        year: 2024,
        url: 'https://carnegieendowment.org/research/2024/12/can-democracy-survive-the-disruptive-power-of-ai',
        type: 'article',
      },
      {
        title: 'The Authoritarian Risks of AI Surveillance',
        author: 'Lawfare',
        year: 2025,
        url: 'https://www.lawfaremedia.org/article/the-authoritarian-risks-of-ai-surveillance',
        type: 'article',
      },
      {
        title: 'The Operational Risks of AI in Large-Scale Biological Attacks',
        author: 'RAND',
        year: 2024,
        url: 'https://www.rand.org/pubs/research_reports/RRA2977-2.html',
        type: 'article',
      },
    ],
  },
  {
    number: 5,
    title: 'Control & Scalable Oversight',
    label: 'Week 5',
    objectives: [
      'Explain the AI control framework and how it differs from alignment, including the assumption that the model may be intentionally subversive',
      'Describe concrete control techniques (resampling, monitoring, trusted models) and evaluate their strengths and limitations',
      'Articulate the core challenge of scalable oversight and assess approaches like weak-to-strong generalization and debate',
    ],
    core: [
      {
        title: 'The Case for Ensuring That Powerful AIs Are Controlled',
        author: 'Redwood Research',
        year: 2024,
        url: 'https://blog.redwoodresearch.org/p/the-case-for-ensuring-that-powerful',
        type: 'blog',
      },
      {
        title: 'Using Dangerous AI, But Safely?',
        author: 'Robert Miles AI Safety',
        year: 2024,
        url: 'https://www.youtube.com/watch?v=0pgEMWy70Qk',
        type: 'video',
      },
      {
        title: 'On Scalable Oversight With Weak LLMs Judging Strong LLMs',
        author: 'Google DeepMind',
        year: 2024,
        url: 'https://www.lesswrong.com/posts/Qn3ZDf9WAqGuAjWQe/on-scalable-oversight-with-weak-llms-judging-strong-llms',
        type: 'paper',
      },
      {
        title: 'Weak-to-Strong Generalization',
        author: 'OpenAI',
        year: 2023,
        url: 'https://cdn.openai.com/papers/weak-to-strong-generalization.pdf',
        type: 'paper',
      },
    ],
    recommended: [
      {
        title: 'AI Control LessWrong Sequence',
        author: 'Various',
        url: 'https://www.lesswrong.com/s/PC3yJgdKvk8kzqZyA',
        type: 'essay',
      },
      {
        title: 'How Can We Solve Diffuse Threats?',
        author: 'Redwood Research',
        url: 'https://blog.redwoodresearch.org/p/how-can-we-solve-diffuse-threats',
        type: 'blog',
      },
      {
        title: 'Ctrl-Z: Controlling AI Agents via Resampling',
        author: 'Redwood Research',
        year: 2025,
        url: 'https://www.lesswrong.com/posts/LPHMMMZFAWog6ty5x/',
        type: 'paper',
      },
      {
        title: 'Simple Probes Can Catch Sleeper Agents',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/probes-catch-sleeper-agents',
        type: 'paper',
      },
      {
        title: 'Debating With More Persuasive LLMs Leads to More Truthful Answers',
        author: 'Khan et al.',
        year: 2024,
        url: 'https://arxiv.org/pdf/2402.06782.pdf',
        type: 'paper',
      },
      {
        title: 'Combining W2SG With Scalable Oversight',
        author: 'Jan Leike',
        year: 2023,
        url: 'https://aligned.substack.com/p/combining-w2sg-with-scalable-oversight',
        type: 'blog',
      },
      {
        title: 'Humans Consulting HCH',
        author: 'Paul Christiano',
        year: 2016,
        url: 'https://ai-alignment.com/humans-consulting-hch-f893f6051455',
        type: 'blog',
      },
      {
        title: 'Measuring Progress on Scalable Oversight for Large Language Models',
        author: 'Bowman et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2211.03540',
        type: 'paper',
      },
      {
        title: 'Debate Update: Obfuscated Arguments Problem',
        author: 'Barnes & Christiano',
        year: 2020,
        url: 'https://www.alignmentforum.org/posts/PJLABqQ962hZEqhdB/',
        type: 'blog',
      },
    ],
    further: [
      {
        title: 'AI Safety via Debate',
        author: 'Irving, Christiano, Amodei',
        year: 2018,
        url: 'https://arxiv.org/abs/1805.00899',
        type: 'paper',
      },
      {
        title: 'Supervising Strong Learners by Amplifying Weak Experts',
        author: 'Christiano, Shlegeris, Amodei',
        year: 2018,
        url: 'https://arxiv.org/abs/1810.08575',
        type: 'paper',
      },
      {
        title: 'How to Prevent Collusion When Using Untrusted Models to Monitor Each Other',
        author: 'Shlegeris (Redwood)',
        year: 2024,
        url: 'https://blog.redwoodresearch.org/p/how-to-prevent-collusion-when-using',
        type: 'blog',
      },
      {
        title: 'Thoughts on the Conservative Assumptions in AI Control',
        author: 'Shlegeris (Redwood)',
        year: 2025,
        url: 'https://blog.redwoodresearch.org/p/thoughts-on-the-conservative-assumptions',
        type: 'blog',
      },
      {
        title: 'An Overview of Control Measures',
        author: 'Greenblatt (Redwood)',
        year: 2025,
        url: 'https://blog.redwoodresearch.org/p/an-overview-of-control-measures',
        type: 'blog',
      },
      {
        title: 'A Sketch of an AI Control Safety Case',
        author: 'Korbak, Clymer, Hilton, Shlegeris, Irving',
        year: 2025,
        url: 'https://arxiv.org/abs/2501.17315',
        type: 'paper',
      },
      {
        title: 'Subversion Strategy Eval: Can Language Models Statelessly Strategize to Subvert Control Protocols?',
        author: 'Mallen et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2412.12480',
        type: 'paper',
      },
      {
        title: 'An Overview of Areas of Control Work',
        author: 'Greenblatt (Redwood)',
        year: 2025,
        url: 'https://blog.redwoodresearch.org/p/an-overview-of-areas-of-control-work',
        type: 'blog',
      },
      {
        title: 'Four Places Where You Can Put LLM Monitoring',
        author: 'Shlegeris (Redwood)',
        year: 2025,
        url: 'https://blog.redwoodresearch.org/p/four-places-where-you-can-put-llm-monitoring',
        type: 'blog',
      },
      {
        title: 'Misalignment and Strategic Underperformance: Sandbagging and Exploration Hacking',
        author: 'Stastny & Shlegeris (Redwood)',
        year: 2025,
        url: 'https://blog.redwoodresearch.org/',
        type: 'blog',
      },
      {
        title: 'Hidden in Plain Text: Emergence & Mitigation of Steganographic Collusion in LLMs',
        author: 'Mathew et al. (LASR Labs)',
        year: 2024,
        url: 'https://arxiv.org/abs/2410.03768',
        type: 'paper',
      },
      {
        title: 'Detecting Strategic Deception Using Linear Probes',
        author: 'Roger & Greenblatt (Redwood)',
        year: 2024,
        url: 'https://www.redwoodresearch.org/',
        type: 'paper',
      },
      {
        title: 'Debate Helps Supervise Unreliable Experts',
        author: 'Michael et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2311.08702',
        type: 'paper',
      },
      {
        title: 'How to Keep Improving When You\'re Better Than Any Teacher — IDA',
        author: 'Robert Miles',
        year: 2019,
        url: 'https://www.youtube.com/watch?v=v9M2Ho9I9Qo',
        type: 'video',
      },
      {
        title: 'Rob Miles YouTube Explainer of the AI Control Paper',
        author: 'Robert Miles',
        year: 2024,
        url: 'https://www.youtube.com/watch?v=xD6Wm0PoYOo',
        type: 'video',
      },
      {
        title: 'AXRP Episode 27: AI Control With Buck Shlegeris and Ryan Greenblatt',
        author: 'Daniel Filan',
        year: 2024,
        url: 'https://axrp.net/episode/2024/04/11/episode-27-ai-control-buck-shlegeris-ryan-greenblatt.html',
        type: 'article',
      },
      {
        title: '80,000 Hours: Buck Shlegeris on Controlling AI That Wants to Take Over',
        author: 'Robert Wiblin',
        year: 2024,
        url: 'https://80000hours.org/podcast/episodes/buck-shlegeris-ai-control-scheming/',
        type: 'article',
      },
      {
        title: '80,000 Hours: Ryan Greenblatt on AI R&D Automation and Misaligned Takeover',
        author: 'Robert Wiblin',
        year: 2025,
        url: 'https://80000hours.org/podcast/',
        type: 'article',
      },
      {
        title: 'Detecting Misbehavior in Frontier Reasoning Models',
        author: 'Baker et al. (OpenAI)',
        year: 2025,
        url: 'https://openai.com/index/chain-of-thought-monitoring/',
        type: 'blog',
      },
      {
        title: 'Chain of Thought Monitorability: A New and Fragile Opportunity for AI Safety',
        author: 'Korbak et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2507.11473',
        type: 'paper',
      },
      {
        title: 'Reasoning Models Don\'t Always Say What They Think',
        author: 'Chen et al. (Anthropic/OpenAI)',
        year: 2025,
        url: 'https://arxiv.org/abs/2505.05410',
        type: 'paper',
      },
      {
        title: 'Monitoring Monitorability',
        author: 'Guan, Wang, Carroll et al. (OpenAI)',
        year: 2025,
        url: 'https://arxiv.org/abs/2512.18311',
        type: 'paper',
      },
      {
        title: 'Measuring Chain-of-Thought Monitorability Through Faithfulness and Verbosity',
        author: 'Meek et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2510.27378',
        type: 'paper',
      },
      {
        title: 'Measuring Chain of Thought Faithfulness by Unlearning Reasoning Steps',
        author: 'EMNLP',
        year: 2025,
        url: 'https://aclanthology.org/2025.emnlp-main.504.pdf',
        type: 'paper',
      },
      {
        title: 'Language Models Don\'t Always Say What They Think: Unfaithful Explanations in Chain-of-Thought Prompting',
        author: 'Turpin et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2305.04388',
        type: 'paper',
      },
      {
        title: 'Measuring Faithfulness in Chain-of-Thought Reasoning',
        author: 'Lanham et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2307.13702',
        type: 'paper',
      },
      {
        title: 'Chain-of-Thought Reasoning in the Wild: Faithfulness',
        author: 'Arcuschin et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2502.11829',
        type: 'paper',
      },
      {
        title: 'When Chain of Thought Is Necessary, Language Models Struggle to Evade Monitors',
        author: 'Emmons et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2503.11926',
        type: 'paper',
      },
      {
        title: 'CoT Red-Handed: Stress Testing Chain-of-Thought Monitoring',
        author: 'Arnav et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2506.04867',
        type: 'paper',
      },
      {
        title: 'LLMs Can Covertly Sandbag on Capability Evaluations Against Chain-of-Thought Monitoring',
        author: 'Li, Phuong, Siegel',
        year: 2025,
        url: 'https://arxiv.org/abs/2508.00943',
        type: 'paper',
      },
      {
        title: 'Stress Testing Deliberative Alignment for Anti-Scheming Training',
        author: 'Schoen et al. (Apollo Research)',
        year: 2025,
        url: 'https://arxiv.org/abs/2509.15541',
        type: 'paper',
      },
      {
        title: 'Auditing Language Models for Hidden Objectives',
        author: 'Meinke et al. (Anthropic)',
        year: 2025,
        url: 'https://arxiv.org/abs/2503.10965',
        type: 'paper',
      },
      {
        title: 'Preventing Language Models From Hiding Their Reasoning',
        author: 'Roger & Greenblatt (Redwood)',
        year: 2023,
        url: 'https://arxiv.org/abs/2310.18512',
        type: 'paper',
      },
    ],
  },
  {
    number: 6,
    title: 'Interpretability & Evals',
    label: 'Week 6',
    objectives: [
      'Describe at a high level what attribution graphs and linear probes are, and what each lets researchers discover about model internals',
      'Point to at least one concrete finding from modern interp on a frontier model (planning, multi-step reasoning, unfaithful chain of thought, etc.)',
      'Distinguish capability evals, propensity evals, dangerous-capability evals, and alignment audits',
    ],
    core: [
      {
        title: 'Tracing the Thoughts of a Large Language Model',
        author: 'Anthropic',
        year: 2025,
        url: 'https://www.anthropic.com/research/tracing-thoughts-language-model',
        type: 'article',
      },
      {
        title: 'Simple Probes Can Catch Sleeper Agents',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/probes-catch-sleeper-agents',
        type: 'paper',
      },
      {
        title: 'An Early Warning System for Novel AI Risks',
        author: 'Google DeepMind',
        year: 2023,
        url: 'https://deepmind.google/discover/blog/an-early-warning-system-for-novel-ai-risks/',
        type: 'article',
      },
      {
        title: "Translating Claude's Thoughts into Language",
        author: 'Anthropic',
        url: 'https://www.youtube.com/watch?v=j2knrqAzYVY',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'Difficulties with Evaluating a Deception Detector for AIs',
        author: 'Google DeepMind',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.22662',
        type: 'paper',
      },
      {
        title: 'Auditing Language Models for Hidden Objectives',
        author: 'Anthropic',
        year: 2025,
        url: 'https://www.anthropic.com/research/auditing-hidden-objectives',
        type: 'article',
      },
      {
        title: 'Every Benchmark is Broken',
        author: 'Jonathan Gabor',
        year: 2026,
        url: 'https://jonathanpgabor.substack.com/p/every-benchmark-is-broken',
        type: 'blog',
      },
      {
        title: 'Interpretability Dreams',
        author: 'Chris Olah',
        year: 2023,
        url: 'https://transformer-circuits.pub/2023/interpretability-dreams/index.html',
        type: 'essay',
      },
      {
        title: 'Responsible Scaling Policies',
        author: 'METR / ARC Evals',
        year: 2023,
        url: 'https://metr.org/blog/2023-09-26-rsp/',
        type: 'blog',
      },
      {
        title: 'Frontier Models Are Capable of In-Context Scheming',
        author: 'Apollo Research',
        year: 2024,
        url: 'https://arxiv.org/abs/2412.04984',
        type: 'paper',
      },
      {
        title: 'Measuring AI Ability to Complete Long Tasks',
        author: 'METR',
        year: 2025,
        url: 'https://metr.org/blog/2025-03-19-measuring-ai-ability-to-complete-long-tasks/',
        type: 'blog',
      },
      {
        title: 'Demystifying Evals for AI Agents',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',
        type: 'article',
      },
      {
        title: 'EIS III: Broad Critiques of Interpretability Research',
        author: 'Stephen Casper',
        year: 2023,
        url: 'https://www.lesswrong.com/posts/gwG9uqw255gafjYN4/eis-iii-broad-critiques-of-interpretability-research',
        type: 'essay',
      },
    ],
    further: [
      {
        title: 'Toy Models of Superposition',
        author: 'Elhage et al.',
        year: 2022,
        url: 'https://transformer-circuits.pub/2022/toy_model/index.html',
        type: 'paper',
      },
      {
        title: 'Towards Monosemanticity',
        author: 'Bricken, Templeton et al. (Anthropic)',
        year: 2023,
        url: 'https://transformer-circuits.pub/2023/monosemantic-features/index.html',
        type: 'paper',
      },
      {
        title: 'Mapping the Mind of a Large Language Model / Scaling Monosemanticity',
        author: 'Templeton et al. (Anthropic)',
        year: 2024,
        url: 'https://www.anthropic.com/research/mapping-mind-language-model',
        type: 'paper',
      },
      {
        title: 'On the Biology of a Large Language Model',
        author: 'Lindsey et al. (Anthropic)',
        year: 2025,
        url: 'https://transformer-circuits.pub/2025/attribution-graphs/biology.html',
        type: 'paper',
      },
      {
        title: 'Refusal in Language Models Is Mediated by a Single Direction',
        author: 'Arditi et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2406.11717',
        type: 'paper',
      },
      {
        title: 'Emergent Misalignment',
        author: 'Betley et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2502.17424',
        type: 'paper',
      },
      {
        title: 'Persona Features Control Emergent Misalignment',
        author: 'Wang et al. (OpenAI)',
        year: 2025,
        url: 'https://arxiv.org/abs/2506.19823',
        type: 'paper',
      },
      {
        title: 'AI Control: Improving Safety Despite Intentional Subversion',
        author: 'Greenblatt et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2312.06942',
        type: 'paper',
      },
      {
        title: 'Agentic Misalignment: How LLMs Could Be Insider Threats',
        author: 'Lynch et al. (Anthropic)',
        year: 2025,
        url: 'https://www.anthropic.com/research/agentic-misalignment',
        type: 'paper',
      },
      {
        title: 'Auditing Language Models for Hidden Objectives (full paper)',
        author: 'Marks et al. (Anthropic)',
        year: 2025,
        url: 'https://arxiv.org/abs/2503.10965',
        type: 'paper',
      },
      {
        title: 'Building and Evaluating Alignment Auditing Agents',
        author: 'Bricken, Marks et al. (Anthropic)',
        year: 2025,
        url: 'https://alignment.anthropic.com/2025/automated-auditing/',
        type: 'paper',
      },
      {
        title: 'EvilGenie: A Reward Hacking Benchmark',
        author: 'Gabor et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.21654',
        type: 'paper',
      },
      {
        title: 'Sabotage Evaluations for Frontier Models',
        author: 'Benton et al. (Anthropic)',
        year: 2024,
        url: 'https://www.anthropic.com/research/sabotage-evaluations',
        type: 'paper',
      },
      {
        title: 'AI Sandbagging',
        author: 'van der Weij et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2406.07358',
        type: 'paper',
      },
      {
        title: 'The WMDP Benchmark',
        author: 'Li et al.',
        year: 2024,
        url: 'https://wmdp.ai/',
        type: 'paper',
      },
    ],
  },
  {
    number: 7,
    title: 'AI Governance & Liability',
    label: 'Week 7',
    objectives: [
      'Explain why AI liability is difficult under existing tort law and evaluate the tradeoffs of different legal approaches (negligence, strict liability, and state-level statutory frameworks)',
      'Describe how compute governance works as a policy lever — including its use for visibility, allocation, and enforcement — and articulate both its strengths and its limitations',
      'Assess the effectiveness of US semiconductor export controls on China\'s AI ecosystem and explain the broader strategic dynamics they reflect',
    ],
    core: [
      {
        title: 'A Simple Solution to Regulate AI',
        author: 'The Hill',
        year: 2023,
        url: 'https://thehill.com/opinion/technology/4106191-a-simple-solution-to-regulate-ai/',
        type: 'article',
      },
      {
        title: 'We\'re Not Ready for AI Liability',
        author: 'AI Frontiers',
        year: 2024,
        url: 'https://ai-frontiers.org/articles/options-for-ai-liability',
        type: 'article',
      },
      {
        title: 'Computing Power and the Governance of AI',
        author: 'GovAI',
        year: 2024,
        url: 'https://www.governance.ai/analysis/computing-power-and-the-governance-of-ai',
        type: 'article',
      },
      {
        title: 'How US Export Controls Have (and Haven\'t) Curbed Chinese AI',
        author: 'AI Frontiers',
        year: 2024,
        url: 'https://ai-frontiers.org/articles/us-chip-export-controls-china-ai',
        type: 'article',
      },
      {
        title: 'The AI Regulator\'s Toolbox: A List of Concrete AI Governance Practices',
        author: 'Adam Jones',
        year: 2024,
        url: 'https://adamjones.me/blog/ai-regulator-toolbox/',
        type: 'blog',
      },
    ],
    recommended: [
      {
        title: 'Securing Model Weights',
        author: 'RAND',
        year: 2024,
        url: 'https://www.rand.org/pubs/research_briefs/RBA2849-1.html',
        type: 'paper',
      },
      {
        title: 'The Finalized EU AI Act: Implications and Insights',
        author: 'Hoffmann (CSET)',
        year: 2024,
        url: 'https://cset.georgetown.edu/article/the-finalized-eu-artificial-intelligence-act-implications-and-insights/',
        type: 'article',
      },
      {
        title: 'China\'s AI Policy at the Crossroads: Balancing Development and Control in the DeepSeek Era',
        author: 'Sheehan (Carnegie)',
        year: 2025,
        url: 'https://carnegieendowment.org/research/2025/07/chinas-ai-policy-in-the-deepseek-era?lang=en',
        type: 'article',
      },
      {
        title: 'SB 53',
        author: 'California Legislature',
        year: 2025,
        url: 'https://legiscan.com/CA/text/SB53/2025',
        type: 'article',
      },
      {
        title: 'Is China Serious About AI Safety?',
        author: 'Carnegie',
        year: 2024,
        url: 'https://carnegieendowment.org/research/2024/09/is-china-serious-about-ai-safety',
        type: 'article',
      },
      {
        title: 'The State of State AI Law',
        author: 'Carnegie',
        year: 2025,
        url: 'https://carnegieendowment.org/research/2025/07/state-ai-law-whats-coming-now-that-the-federal-moratorium-is-dead?lang=en',
        type: 'article',
      },
      {
        title: 'Frontier AI Regulation: Managing Emerging Risks to Public Safety',
        author: 'Anderljung et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2307.03718',
        type: 'paper',
      },
      {
        title: 'International Institutions for Advanced AI',
        author: 'Ho et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2307.04699',
        type: 'paper',
      },
      {
        title: 'If-Then Commitments for AI Risk Reduction',
        author: 'Carnegie',
        year: 2024,
        url: 'https://carnegieendowment.org/research/2024/09/if-then-commitments-for-ai-risk-reduction',
        type: 'article',
      },
      {
        title: 'Verifying International Agreements on AI',
        author: 'RAND',
        year: 2024,
        url: 'https://www.rand.org/pubs/working_papers/WRA4077-1.html',
        type: 'paper',
      },
      {
        title: 'The Case for AI Liability',
        author: 'AI Frontiers',
        year: 2024,
        url: 'https://ai-frontiers.org/articles/case-for-ai-liability',
        type: 'article',
      },
      {
        title: 'Tort Law as a Tool for Mitigating Catastrophic Risk from AI',
        author: 'Weil',
        year: 2024,
        url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4694006',
        type: 'paper',
      },
    ],
    further: [
      {
        title: 'Trump\'s Plan for AI: Recapping the White House\'s AI Action Plan',
        author: 'Friedland (CSET)',
        year: 2025,
        url: 'https://cset.georgetown.edu/article/trumps-plan-for-ai-recapping-the-white-houses-ai-action-plan/',
        type: 'article',
      },
      {
        title: 'AI Safety Under the EU AI Code of Practice — A New Global Standard?',
        author: 'Hoffmann (CSET)',
        year: 2025,
        url: 'https://cset.georgetown.edu/article/eu-ai-code-safety/',
        type: 'article',
      },
      {
        title: 'AISI Frontier AI Trends Report 2025',
        author: 'UK AI Security Institute',
        year: 2025,
        url: 'https://www.aisi.gov.uk/research/aisi-frontier-ai-trends-report-2025',
        type: 'article',
      },
      {
        title: 'Common Elements of Frontier AI Safety Policies',
        author: 'METR',
        year: 2025,
        url: 'https://metr.org/blog/2025-12-09-common-elements-of-frontier-ai-safety-policies/',
        type: 'blog',
      },
      {
        title: 'The AI Governance Arms Race: From Summit Pageantry to Progress?',
        author: 'Renda (Carnegie)',
        year: 2024,
        url: 'https://carnegieendowment.org/research/2024/10/the-ai-governance-arms-race-from-summit-pageantry-to-progress?lang=en&center=europe',
        type: 'article',
      },
      {
        title: 'Superintelligence Strategy: Expert Version',
        author: 'Hendrycks, Schmidt, & Wang',
        year: 2025,
        url: 'https://files.nationalsecurity.ai/Superintelligence_Strategy.pdf',
        type: 'paper',
      },
      {
        title: 'Seeking Stability in the Competition for AI Advantage',
        author: 'Mazarr (RAND)',
        year: 2025,
        url: 'https://www.rand.org/pubs/commentary/2025/03/seeking-stability-in-the-competition-for-ai-advantage.html',
        type: 'article',
      },
      {
        title: 'Oversight for Frontier AI Through a KYC Scheme for Compute Providers',
        author: 'Egan & Heim (GovAI)',
        year: 2023,
        url: 'https://arxiv.org/abs/2310.13625',
        type: 'paper',
      },
      {
        title: 'Secure, Governable Chips',
        author: 'Aarne, Fist, & Withers (CNAS/IAPS)',
        year: 2024,
        url: 'https://www.cnas.org/publications/reports/secure-governable-chips',
        type: 'paper',
      },
      {
        title: 'Anthropic\'s RSP v3.0: How It Works, What\'s Changed, and Some Reflections',
        author: 'GovAI',
        year: 2025,
        url: 'https://www.governance.ai/analysis/anthropics-rsp-v3-0-how-it-works-whats-changed-and-some-reflections',
        type: 'article',
      },
      {
        title: 'Regulatory Markets',
        author: 'Hadfield & Clark',
        year: 2023,
        url: 'https://arxiv.org/pdf/2304.04914',
        type: 'paper',
      },
      {
        title: 'Situational Awareness: Lock Down the Labs',
        author: 'Aschenbrenner',
        year: 2024,
        url: 'https://situational-awareness.ai/lock-down-the-labs/',
        type: 'essay',
      },
      {
        title: 'A National Center for Advanced AI Reliability and Security',
        author: 'FAS',
        year: 2024,
        url: 'https://fas.org/publication/a-national-center-for-advanced-ai-reliability-and-security/',
        type: 'article',
      },
      {
        title: 'U.S. Tort Liability for Large-Scale AI Damages: A Primer',
        author: 'Ramakrishnan et al. (RAND)',
        year: 2024,
        url: 'https://www.rand.org/pubs/research_reports/RRA3084-1.html',
        type: 'paper',
      },
      {
        title: 'Tort Law and Frontier AI Governance',
        author: 'van der Merwe, Ramakrishnan, & Anderljung (Lawfare)',
        year: 2024,
        url: 'https://www.lawfaremedia.org/article/tort-law-and-frontier-ai-governance',
        type: 'article',
      },
      {
        title: 'Tort Law Should Be the Centerpiece of AI Governance',
        author: 'Weil (Lawfare)',
        year: 2024,
        url: 'https://www.lawfaremedia.org/article/tort-law-should-be-the-centerpiece-of-ai-governance',
        type: 'article',
      },
    ],
  },
  {
    number: 8,
    title: 'Careers in AI Safety',
    label: 'Week 8',
    comingSoon: true,
  },
]
