export type ReadingType = 'paper' | 'blog' | 'video' | 'article' | 'essay' | 'guide'

export type Reading = {
  title: string
  author: string
  year?: number
  url: string
  type: ReadingType
}

export type Week = {
  number: number
  title: string
  label: string
  comingSoon?: boolean
  objectives?: string[]
  core?: Reading[]
  recommended?: Reading[]
  further?: Reading[]
}

export const weeks: Week[] = [
  {
    number: 0,
    title: 'Introduction to Machine Learning',
    label: 'Self-Paced',
    objectives: [
      'Explain how neural networks are trained at a high level',
      'Describe the basic transformer architecture',
    ],
    core: [
      {
        title: 'Neural Networks (Chapters 1-6)',
        author: '3Blue1Brown',
        year: 2024,
        url: 'https://youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'What is Self-Supervised Learning?',
        author: 'CodeBasics',
        year: 2021,
        url: 'https://youtu.be/sJzuNAisXHA',
        type: 'video',
      },
      {
        title: 'Transformers from Scratch',
        author: 'Brandon Rohrer',
        year: 2021,
        url: 'https://e2eml.school/transformers.html',
        type: 'guide',
      },
      {
        title: 'The Spelled-Out Intro to Neural Networks and Backpropagation',
        author: 'Andrej Karpathy',
        year: 2022,
        url: 'https://youtu.be/VMj-3S1tku0',
        type: 'video',
      },
      {
        title: 'Machine Learning for Humans, Part 2.1: Supervised Learning',
        author: 'Maini & Sabri',
        year: 2017,
        url: 'https://medium.com/@v_maini/supervised-learning-740383a2feab',
        type: 'article',
      },
    ],
  },
  {
    number: 1,
    title: 'Transformative AI and Current Trajectory',
    label: 'Week 1',
    objectives: [
      'Describe current AI capability trends and their real-world impacts',
      'Understand arguments for acceleration versus slowdown trajectories',
      'Comprehend scaling drivers: compute, data, algorithmic efficiency, and inference-time scaling',
    ],
    core: [
      {
        title: 'METR Time Horizon',
        author: 'METR',
        year: 2026,
        url: 'https://metr.org/time-horizons/',
        type: 'article',
      },
      {
        title: 'Epoch AI Trends Page',
        author: 'Epoch AI',
        year: 2025,
        url: 'https://epochai.org/trends',
        type: 'article',
      },
      {
        title: 'Can AI Scaling Continue Through 2030?',
        author: 'Epoch AI',
        year: 2024,
        url: 'https://epoch.ai/blog/can-ai-scaling-continue-through-2030',
        type: 'blog',
      },
      {
        title: 'The Power of Intelligence',
        author: 'Eliezer Yudkowsky',
        year: 2007,
        url: 'https://youtu.be/q9Figerh89g?si=9gOTbCyKqrbU6nPp',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'What Will AI Look Like in 2030?',
        author: 'Epoch AI',
        year: 2025,
        url: 'https://epoch.ai/blog/what-will-ai-look-like-in-2030',
        type: 'blog',
      },
      {
        title: 'From AGI to Superintelligence: The Intelligence Explosion',
        author: 'Leopold Aschenbrenner',
        year: 2024,
        url: 'https://situational-awareness.ai/from-agi-to-superintelligence/',
        type: 'essay',
      },
      {
        title: 'Inference Scaling and the Log-x Chart',
        author: 'Toby Ord',
        year: 2025,
        url: 'https://forum.effectivealtruism.org/posts/zNymXezwySidkeRun/inference-scaling-and-the-log-x-chart',
        type: 'essay',
      },
    ],
    further: [
      {
        title: 'Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity',
        author: 'METR',
        year: 2025,
        url: 'https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/',
        type: 'article',
      },
      {
        title: 'Future ML Systems Will Be Qualitatively Different',
        author: 'Jacob Steinhardt',
        year: 2022,
        url: 'https://bounded-regret.ghost.io/future-ml-systems-will-be-qualitatively-different/',
        type: 'blog',
      },
      {
        title: 'Neural Scaling Laws and GPT-3',
        author: 'Kaplan',
        year: 2020,
        url: 'https://www.youtube.com/watch?v=QMqPAM_knrE',
        type: 'video',
      },
      {
        title: 'Training Compute-Optimal Large Language Models',
        author: 'Hoffmann et al. (DeepMind)',
        year: 2022,
        url: 'https://arxiv.org/pdf/2203.15556.pdf',
        type: 'paper',
      },
      {
        title: 'Biological Anchors: A Trick That Might Or Might Not Work',
        author: 'Scott Alexander',
        year: 2022,
        url: 'https://astralcodexten.substack.com/p/biological-anchors-a-trick-that-might',
        type: 'blog',
      },
      {
        title: 'Explaining Neural Scaling Laws',
        author: 'Bahri et al.',
        year: 2024,
        url: 'https://arxiv.org/abs/2102.06701',
        type: 'paper',
      },
      {
        title: 'The Hanson-Yudkowsky AI-Foom Debate',
        author: 'Hanson & Yudkowsky',
        year: 2008,
        url: 'https://intelligence.org/files/AIFoomDebate.pdf',
        type: 'essay',
      },
    ],
  },
  {
    number: 2,
    title: 'Outer Alignment',
    label: 'Week 2',
    objectives: [
      'Understand the gap between intended goals and proxy training objectives',
      'Identify major outer alignment failure modes: specification gaming, reward hacking',
      'Evaluate how RLHF and reward modeling advance but don\'t fully resolve alignment',
    ],
    core: [
      {
        title: 'Specification Gaming: The Flip Side of AI Ingenuity',
        author: 'DeepMind',
        year: 2020,
        url: 'https://www.deepmind.com/blog/specification-gaming-the-flip-side-of-ai-ingenuity',
        type: 'blog',
      },
      {
        title: 'Aligning Language Models to Follow Instructions',
        author: 'OpenAI',
        year: 2022,
        url: 'https://openai.com/blog/instruction-following/',
        type: 'blog',
      },
      {
        title: 'Language Models Learn to Mislead Humans via RLHF',
        author: 'Wen et al.',
        year: 2024,
        url: 'https://arxiv.org/pdf/2409.12822',
        type: 'paper',
      },
      {
        title: 'Large Language Models Can Strategically Deceive Their Users When Put Under Pressure',
        author: 'Apollo Research',
        year: 2023,
        url: 'https://arxiv.org/pdf/2311.07590',
        type: 'paper',
      },
    ],
    recommended: [
      {
        title: 'Deep RL From Human Preferences',
        author: 'Christiano et al.',
        year: 2017,
        url: 'https://openai.com/blog/deep-reinforcement-learning-from-human-preferences/',
        type: 'blog',
      },
      {
        title: 'Playing the Training Game',
        author: 'Kelsey Piper',
        year: 2023,
        url: 'https://www.planned-obsolescence.org/the-training-game/',
        type: 'essay',
      },
      {
        title: 'Natural Emergent Misalignment From Reward Hacking in Production RL',
        author: 'Anthropic & Redwood Research',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.18397',
        type: 'paper',
      },
      {
        title: 'Constitutional AI: Harmlessness From AI Feedback',
        author: 'Anthropic',
        year: 2022,
        url: 'https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback',
        type: 'paper',
      },
      {
        title: 'Open Problems and Fundamental Limitations of RLHF',
        author: 'Casper et al.',
        year: 2023,
        url: 'https://arxiv.org/abs/2307.15217',
        type: 'paper',
      },
    ],
    further: [
      {
        title: 'Sycophancy to Subterfuge: Investigating Reward Tampering in Language Models',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/reward-tampering',
        type: 'paper',
      },
      {
        title: 'Scaling Laws for Reward Model Overoptimization',
        author: 'OpenAI',
        year: 2022,
        url: 'https://arxiv.org/abs/2210.10760',
        type: 'paper',
      },
      {
        title: 'Concrete Problems in AI Safety',
        author: 'Amodei et al.',
        year: 2016,
        url: 'https://arxiv.org/abs/1606.06565',
        type: 'paper',
      },
      {
        title: 'Scalable Agent Alignment via Reward Modeling',
        author: 'DeepMind',
        year: 2018,
        url: 'https://arxiv.org/abs/1811.07871',
        type: 'paper',
      },
    ],
  },
  {
    number: 3,
    title: 'Inner Alignment',
    label: 'Week 3',
    objectives: [
      'Describe key failure modes: mesa-optimization, goal misgeneralization, deceptive alignment',
      'Evaluate empirical evidence that models fake alignment and persist deceptively through safety training',
      'Assess why standard safety training may be insufficient against deceptively misaligned behavior',
    ],
    core: [
      {
        title: 'The OTHER AI Alignment Problem: Mesa-Optimizers and Inner Alignment',
        author: 'Robert Miles',
        year: 2021,
        url: 'https://www.youtube.com/watch?v=bJLcIBixGj8',
        type: 'video',
      },
      {
        title: 'Alignment Faking in Large Language Models',
        author: 'Anthropic & Redwood Research',
        year: 2024,
        url: 'https://arxiv.org/abs/2412.14093',
        type: 'paper',
      },
      {
        title: 'Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training',
        author: 'Anthropic',
        year: 2024,
        url: 'https://arxiv.org/abs/2401.05566',
        type: 'paper',
      },
      {
        title: 'From Shortcuts to Sabotage: Natural Emergent Misalignment From Reward Hacking',
        author: 'Anthropic',
        year: 2025,
        url: 'https://arxiv.org/abs/2511.18397',
        type: 'paper',
      },
    ],
    recommended: [
      {
        title: 'ML Systems Will Have Weird Failure Modes',
        author: 'Jacob Steinhardt',
        year: 2022,
        url: 'https://bounded-regret.ghost.io/ml-systems-will-have-weird-failure-modes-2/',
        type: 'blog',
      },
      {
        title: 'Sycophancy to Subterfuge: Investigating Reward Tampering in Language Models',
        author: 'Anthropic',
        year: 2024,
        url: 'https://www.anthropic.com/research/reward-tampering',
        type: 'paper',
      },
      {
        title: 'Emergent Misalignment: Narrow Finetuning Can Produce Broadly Misaligned LLMs',
        author: 'Betley et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2502.07209',
        type: 'paper',
      },
      {
        title: 'Frontier Models are Capable of In-Context Scheming',
        author: 'Apollo Research',
        year: 2024,
        url: 'https://www.apolloresearch.ai/research/frontier-models-are-capable-of-in-context-scheming/',
        type: 'article',
      },
      {
        title: 'Distillation of "How Likely is Deceptive Alignment?"',
        author: 'Evan Hubinger',
        year: 2022,
        url: 'https://www.lesswrong.com/posts/XKraEJrQRfzbCtzKN/distillation-of-how-likely-is-deceptive-alignment',
        type: 'essay',
      },
    ],
    further: [
      {
        title: 'Why Alignment Could Be Hard With Modern Deep Learning',
        author: 'Ajeya Cotra',
        year: 2021,
        url: 'https://www.alignmentforum.org/posts/CoZhXrhpQxpy88Sq8/why-alignment-could-be-hard-with-modern-deep-learning',
        type: 'essay',
      },
      {
        title: 'Goal Misgeneralization: Why Correct Specifications Aren\'t Enough for Correct Goals',
        author: 'Shah et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2210.01790',
        type: 'paper',
      },
      {
        title: 'The Alignment Problem From a Deep Learning Perspective',
        author: 'Ngo et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2209.00626',
        type: 'paper',
      },
      {
        title: 'Goal Misgeneralization in Deep Reinforcement Learning',
        author: 'Langosco et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/2105.14111',
        type: 'paper',
      },
      {
        title: 'Optimal Policies Tend to Seek Power',
        author: 'Turner et al.',
        year: 2022,
        url: 'https://arxiv.org/abs/1906.01820',
        type: 'paper',
      },
      {
        title: 'Language Models as Agent Models',
        author: 'Andreas',
        year: 2022,
        url: 'https://arxiv.org/abs/2212.01681',
        type: 'paper',
      },
    ],
  },
  {
    number: 4,
    title: 'Threat Models',
    label: 'Week 4',
    objectives: [
      'Articulate the orthogonality thesis and instrumental convergence and their centrality to advanced AI risk',
      'Connect technical alignment failures to real-world harm scenarios at scale',
    ],
    core: [
      {
        title: 'What is the Orthogonality Thesis?',
        author: 'AISafety.info',
        url: 'https://aisafety.info/questions/6568/What-is-the-orthogonality-thesis',
        type: 'article',
      },
      {
        title: 'Why Would AI Want to do Bad Things? Instrumental Convergence',
        author: 'Robert Miles',
        year: 2018,
        url: 'https://www.youtube.com/watch?v=ZeecOKBus3Q',
        type: 'video',
      },
      {
        title: 'Statement on AI Risk',
        author: 'Center for AI Safety',
        year: 2023,
        url: 'https://safe.ai/work/statement-on-ai-risk',
        type: 'article',
      },
      {
        title: 'An Overview of Catastrophic AI Risks',
        author: 'Center for AI Safety',
        year: 2023,
        url: 'https://arxiv.org/abs/2306.12001',
        type: 'paper',
      },
      {
        title: 'We\'re Not Ready for Superintelligence',
        author: 'AI in Context',
        year: 2025,
        url: 'https://www.youtube.com/watch?v=5KVDDfAkRgc',
        type: 'video',
      },
    ],
    recommended: [
      {
        title: 'AI 2027',
        author: 'AI Futures Project',
        year: 2025,
        url: 'https://ai-2027.com/',
        type: 'article',
      },
      {
        title: 'The Problem',
        author: 'MIRI',
        year: 2025,
        url: 'https://intelligence.org/the-problem/',
        type: 'article',
      },
      {
        title: 'Intelligence and Stupidity: The Orthogonality Thesis',
        author: 'Robert Miles',
        year: 2018,
        url: 'https://www.youtube.com/watch?v=hEUO6pjwFOo',
        type: 'video',
      },
      {
        title: 'The Basic AI Drives',
        author: 'Steve Omohundro',
        year: 2008,
        url: 'https://selfawaresystems.com/wp-content/uploads/2008/01/ai_drives_final.pdf',
        type: 'paper',
      },
      {
        title: 'Gradual Disempowerment',
        author: 'Kulveit et al.',
        year: 2025,
        url: 'https://arxiv.org/abs/2501.16946',
        type: 'paper',
      },
      {
        title: 'The Superintelligent Will: Motivation and Instrumental Rationality in Advanced Artificial Agents',
        author: 'Nick Bostrom',
        year: 2012,
        url: 'https://nickbostrom.com/superintelligentwill.pdf',
        type: 'paper',
      },
      {
        title: 'Existential Risk from Power-Seeking AI',
        author: 'Joe Carlsmith',
        year: 2022,
        url: 'https://arxiv.org/abs/2206.13353',
        type: 'paper',
      },
    ],
    further: [
      {
        title: 'Instrumental Convergence',
        author: 'Eliezer Yudkowsky',
        year: 2025,
        url: 'https://arbital.com/p/instrumental_convergence/',
        type: 'article',
      },
      {
        title: 'Why Would AI "Aim" To Defeat Humanity?',
        author: 'Cold Takes',
        year: 2022,
        url: 'https://www.cold-takes.com/why-would-ai-aim-to-defeat-humanity/',
        type: 'blog',
      },
      {
        title: 'AI Could Defeat All Of Us Combined',
        author: 'Cold Takes',
        year: 2022,
        url: 'https://www.cold-takes.com/ai-could-defeat-all-of-us-combined/',
        type: 'blog',
      },
      {
        title: 'Two Types of AI Existential Risk: Decisive and Accumulative',
        author: 'Atoosa Kasirzadeh',
        year: 2025,
        url: 'https://arxiv.org/abs/2401.07836',
        type: 'paper',
      },
      {
        title: 'International AI Safety Report 2026',
        author: 'International AI Safety Report',
        year: 2026,
        url: 'https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026',
        type: 'article',
      },
      {
        title: 'The Vulnerable World Hypothesis',
        author: 'Nick Bostrom',
        year: 2019,
        url: 'https://nickbostrom.com/papers/vulnerable.pdf',
        type: 'paper',
      },
      {
        title: 'AI-Enabled Coups: How a Small Group Could Use AI to Seize Power',
        author: 'Forethought',
        year: 2025,
        url: 'https://www.forethought.org/research/ai-enabled-coups-how-a-small-group-could-use-ai-to-seize-power',
        type: 'article',
      },
      {
        title: 'Impact of AI on Cyber Threat From Now to 2027',
        author: 'NCSC',
        year: 2025,
        url: 'https://www.ncsc.gov.uk/report/impact-ai-cyber-threat-now-2027',
        type: 'article',
      },
      {
        title: 'How AI Threatens Democracy',
        author: 'Kreps & Kriner',
        year: 2023,
        url: 'https://www.journalofdemocracy.org/articles/how-ai-threatens-democracy/',
        type: 'article',
      },
      {
        title: 'Can Democracy Survive the Disruptive Power of AI?',
        author: 'Carnegie Endowment',
        year: 2024,
        url: 'https://carnegieendowment.org/research/2024/12/can-democracy-survive-the-disruptive-power-of-ai',
        type: 'article',
      },
      {
        title: 'The Authoritarian Risks of AI Surveillance',
        author: 'Lawfare',
        year: 2025,
        url: 'https://www.lawfaremedia.org/article/the-authoritarian-risks-of-ai-surveillance',
        type: 'article',
      },
      {
        title: 'The Operational Risks of AI in Large-Scale Biological Attacks',
        author: 'RAND',
        year: 2024,
        url: 'https://www.rand.org/pubs/research_reports/RRA2977-2.html',
        type: 'article',
      },
    ],
  },
  {
    number: 5,
    title: 'AI Control',
    label: 'Week 5',
    comingSoon: true,
  },
  {
    number: 6,
    title: 'Interpretability',
    label: 'Week 6',
    comingSoon: true,
  },
  {
    number: 7,
    title: 'Policy',
    label: 'Week 7',
    comingSoon: true,
  },
  {
    number: 8,
    title: 'Careers in AI Safety',
    label: 'Week 8',
    comingSoon: true,
  },
]
